# This is just to create a local database for testing node.js functions locally
version: '3.1'

services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
  migrate-dynamo:
    image: amazon/aws-cli
    entrypoint: /bin/bash
    network_mode: host
    environment:
      AWS_ACCESS_KEY_ID: DEFAULT_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY: DEFAULT_SECRET
      TABLE_NAME: zombo-sls-dev-table
    command: >
      -c "curl -o /usr/bin/wait-for-it https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
      && chmod 555 /usr/bin/wait-for-it
      && wait-for-it localhost:8000
      && aws dynamodb create-table    --table-name=$${TABLE_NAME}    --attribute-definitions AttributeName=ip,AttributeType=S AttributeName=path,AttributeType=S    --key-schema AttributeName=ip,KeyType=HASH AttributeName=path,KeyType=RANGE    --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5    --endpoint-url http://localhost:8000 --region localhost
      "

