version: "2.1"
volumes:
  mysqldb:
services:

  phpmyadmin:
    image: phpmyadmin

    environment:
      PMA_USER: admin
      PMA_PASSWORD: admin
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_PASSWORD: admin

   # volumes:
   #   - workbench:/config
    ports:
      - 8080:80

  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: phpmyadmindb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin

    volumes:
      - mysqldb:/var/lib/mysql
    ports:
      - 3306:3306

    #cap_add:
    #  - IPC_LOCK
    #restart: always
